<?php

namespace WalkAroundBundle\Repository;

/**
 * CommentDestinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentDestinationRepository extends \Doctrine\ORM\EntityRepository
{
}
