<?php

namespace WalkAroundBundle\Repository;

/**
 * CommentDestinationLikedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentDestinationLikedRepository extends \Doctrine\ORM\EntityRepository
{
}
