<?php

namespace WalkAroundBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\OptimisticLockException;
use WalkAroundBundle\Entity\CommentDestinationLiked;

/**
 * CommentDestinationLikedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentDestinationLikedRepository extends EntityRepository
{
    public function __construct( EntityManagerInterface $em, Mapping\ClassMetadata $class = null )
    {
        /** @var EntityManager $em */
        parent::__construct($em, $class == null ? new Mapping\ClassMetadata( CommentDestinationLiked::class ) : $class );
    }

    public function insert( CommentDestinationLiked $like ) {
        try{
            $this->_em->persist( $like );
            $this->_em->flush();
            return true;
        } catch ( OptimisticLockException $e ) {
            return false;
        }
    }
    public function update( CommentDestinationLiked $like ) {

        try{
            $this->_em->merge( $like );
            $this->_em->flush();
            return true;
        } catch ( OptimisticLockException $e ) {
            return false;
        }
    }
    public function delete( CommentDestinationLiked $like ) {
        try{
            $this->_em->remove( $like );
            $this->_em->flush();
            return true;
        } catch ( OptimisticLockException $e ) {
            return false;
        }
    }
}
