<?php

namespace WalkAroundBundle\Repository;

/**
 * DestinationLikedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinationLikedRepository extends \Doctrine\ORM\EntityRepository
{
}
