<?php

namespace WalkAroundBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\OptimisticLockException;
use WalkAroundBundle\Entity\Event;
use WalkAroundBundle\Entity\EventComment;

/**
 * EventCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCommentRepository extends EntityRepository
{
    public function __construct( EntityManagerInterface $em, Mapping\ClassMetadata $class = null )
    {
        /** @var EntityManager $em */
        parent::__construct($em, $class == null ? new Mapping\ClassMetadata( EventComment::class ) : $class );
    }

    public function insert( EventComment $comment ) {
        try{
            $this->_em->persist( $comment );
            $this->_em->flush();
            return true;
        } catch ( OptimisticLockException $e ) {
            return false;
        }
    }
    public function update( EventComment $comment ) {

        try{
            $this->_em->merge( $comment );
            $this->_em->flush();
            return true;
        } catch ( OptimisticLockException $e ) {
            return false;
        }
    }
    public function delete( EventComment $comment ) {
        try{
            $this->_em->remove( $comment );
            $this->_em->flush();
            return true;
        } catch ( OptimisticLockException $e ) {
            return false;
        }
    }

    /**
     * @param Event $event
     * @return EventComment[]
     */
    public function findOneByevent( Event $event) {
        $query = $this->createQueryBuilder('c')
            ->where('c.eventId = :id')
            ->setParameter('id', $event->getId())
            ->getQuery();

        $products = $query->getResult();
        return $products;
    }
}
