<?php

namespace WalkAroundBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\OptimisticLockException;
use WalkAroundBundle\Entity\Event;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function __construct( EntityManagerInterface $em, Mapping\ClassMetadata $class = null )
    {
        /** @var EntityManager $em */
        parent::__construct($em, $class == null ? new Mapping\ClassMetadata( Event::class ) : $class );
    }


    public function insert( Event $event ) {
        try{
            $this->_em->persist( $event );
            $this->_em->flush();
            return true;
        } catch ( OptimisticLockException $e ) {
            return false;
        }
    }
    public function update( Event $event ) {

        try{
            $this->_em->merge( $event );
            $this->_em->flush();
            return true;
        } catch ( OptimisticLockException $e ) {
            return false;
        }
    }
    public function delete( Event $event ) {
        try{
            $this->_em->remove( $event );
            $this->_em->flush();
            return true;
        } catch ( OptimisticLockException $e ) {
            return false;
        }
    }

   public function findOneByNull( Event $event) {
       $query = $this->createQueryBuilder('event')
           ->where('event.id = :id')
           ->andWhere('event.endOn = :n')
           ->setParameter('id', $event->getId() )
           ->setParameter('n', NULL)
           ->getQuery();

       $products = $query->getResult();

       return $products;
   }

}
