<?php

namespace WalkAroundBundle\Repository;

/**
 * EventCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
