<?php

namespace WalkAroundBundle\Repository;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\OptimisticLockException;
use WalkAroundBundle\Entity\Friendship;

/**
 * FriendshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendshipRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct( EntityManagerInterface $em, Mapping\ClassMetadata $class = null )
    {
        /** @var EntityManager $em */
        parent::__construct($em, $class == null ? new Mapping\ClassMetadata( Friendship::class ) : $class );
    }

    /**
     * @param Friendship $friendship
     * @return bool
     */
    public function insert( Friendship $friendship) :bool {
        try{
            $this->_em->persist( $friendship );
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Friendship $friendship
     * @return bool
     */
    public function update( Friendship $friendship) {
        try{
            $this->_em->persist( $friendship );
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Friendship $friendship
     * @return bool
     */
    public function delete(Friendship $friendship)
    {
        try{
            $this->_em->remove( $friendship );
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

}
