<?php

namespace WalkAroundBundle\Repository;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\OptimisticLockException;
use WalkAroundBundle\Entity\Region;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository
{
    public function __construct( EntityManagerInterface $em, Mapping\ClassMetadata $class = null )
    {
        /** @var EntityManager $em */
        parent::__construct($em, $class == null ? new Mapping\ClassMetadata( Region::class ) : $class );
    }

    /**
     * @param Region $region
     * @return bool
     */
    public function insert( Region $region) :bool {
        try{
            $this->_em->persist( $region );
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Region $region
     * @return bool
     */
    public function update( Region $region) {
        try{
            $this->_em->persist( $region );
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Region $region
     * @return bool
     */
    public function delete(Region $region)
    {
        try{
            $this->_em->remove( $region );
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @return Region[]
     */
    public function findAllOrderByName()
    {
        return $this->findBy([], ['name' => 'ASC']);

    }

}
